GET http://fit-quest.ru/api/cat
Cookie: accessToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NDgxOTgxNjgsImlhdCI6MTc0ODE5NDU2OCwidXNlcklkIjoiYmMxNDJjYzctMjc4Yi00NWZmLWE0NzItOGE5ZDVjOTQwYmJmIn0.8hIl_eg9w-tIbh9oywouGw_BRUu0SVGvM8zcY3_O_lQ
# Response 1 просто пример аутентифицированного запроса
    # HTTP/1.1 200 OK
    # Content-Type: application/json
    # Content-Length: 133

    # {
    #   "message": "Кот специально для John Doe",
    #   "cat": " /\_/\                  
    #           ( o.o )                   
    #            > ^ <"
    # }

# Response 2
    # HTTP/1.1 401 Unauthorized
    # Date: Mon, 05 May 2025 18:00:04 GMT
    # Connection: close
    # Content-Length: 0
    # WWW-Authenticate: Bearer realm=""