GET http://localhost:8080/api/cat
Cookie: accessToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NDc5NDAwNDgsImlhdCI6MTc0NzkzNjQ0OCwidXNlcklkIjoiNGI0MTY3ZTMtNzIxNy00MGY2LWEzZmQtZjk3OWViYWZlNzM4In0.qyY1WLi-iqGgFWfISw6jT7KGHdwEIEuvy27xbuIJr3s;refreshToken=I9BeEIngbDXRSiHsrH_GdC63OjqYtXePYXDd3_7LP07oDAC9GXPUuY087xuvLwXl4I8e6mupHo6NqJ8Z5AU7TQ; Max-Age=604800;
# Response 1 просто пример аутентифицированного запроса
    # HTTP/1.1 200 OK
    # Content-Type: application/json
    # Content-Length: 133

    # {
    #   "message": "Кот специально для John Doe",
    #   "cat": " /\_/\                  
    #           ( o.o )                   
    #            > ^ <"
    # }

# Response 2
    # HTTP/1.1 401 Unauthorized
    # Date: Mon, 05 May 2025 18:00:04 GMT
    # Connection: close
    # Content-Length: 0
    # WWW-Authenticate: Bearer realm=""