GET http://fit-quest.ru/api/exercises?offset=0&limit=10
Content-Type: application/json
Cookie: accessToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NDgyMDAwODQsImlhdCI6MTc0ODE5NjQ4NCwidXNlcklkIjoiNjFlNjRjM2UtMGIwMS00YjU0LTlkNGUtYzZjMzgyNzIzNGM0In0.5xgHHWs2Eu-HR5xvquk2wuRZq6QZJC4WZay2ijpDlzU