POST http://localhost:8080/api/auth/refresh
Cookie: accessToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NDc5NDAwNDgsImlhdCI6MTc0NzkzNjQ0OCwidXNlcklkIjoiNGI0MTY3ZTMtNzIxNy00MGY2LWEzZmQtZjk3OWViYWZlNzM4In0.qyY1WLi-iqGgFWfISw6jT7KGHdwEIEuvy27xbuIJr3s;refreshToken=I9BeEIngbDXRSiHsrH_GdC63OjqYtXePYXDd3_7LP07oDAC9GXPUuY087xuvLwXl4I8e6mupHo6NqJ8Z5AU7TQ; Max-Age=604800;

# Response 1
    # HTTP/1.1 200 OK
    # Content-Length: 0
    # Set-Cookie: accessToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NDY0NzEwNzUsImlhdCI6MTc0NjQ2NzQ3NSwidXNlcklkIjoiMWYzZjQ5YjAtZjYxYS00OThlLWEwNjYtYjhkNTQ4ZDIwMTFlIn0.dYtdJhLhCATv1UVl-GiZby7hh13tbSvvmZff_Lw813g; Max-Age=3600; Path=/api/; SameSite=Strict; Secure,refreshToken=z5ESEIEO1nf-IdzrpZleNRo_hW04f4DlALiY0zt2nyQD09W_zHU_1OY-44QTVRusGksG2PhyI423YamLsafL9A; Max-Age=604800; Path=/api/api/auth/refresh/; SameSite=Strict; Secure; HttpOnly

# Response 2 когда токен не существует, использован, или просрочен
    # HTTP/1.1 400 Bad Request
    # Content-Type: text/plain; charset=UTF-8
    # Content-Length: 16

    # Token is invalid

# Response 3, когда токена нет в куках
    # HTTP/1.1 400 Bad Request
    # Content-Type: text/plain; charset=UTF-8
    # Content-Length: 23

    # Refresh token not found
