services:
  db:
    image: postgres
    restart: always
    volumes:
      - "./docker-init/db:/docker-entrypoint-initdb.d"
    environment:
      - "POSTGRES_USER=docker2"
      - "POSTGRES_PASSWORD=docker2"
      - "POSTGRES_DB=mydb"
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080

  app:
    image: andreyegor/backend:latest
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/mydb
      DB_USER: docker2
      DB_PASSWORD: docker2
    ports:
      - "8080:8080"
