POST http://localhost:8080/api/user/add
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john_doe@example.com",
    "password": "the-amazing-spider-password"
}

# Response 1:
    # HTTP/1.1 201 Created
    # Date: ...
    # Connection: close
    # Content-Length: 0

# Response 2:
    # HTTP/1.1 409 Conflict
    # Date: ...
    # Connection: close
    # Content-Type: text/plain; charset=UTF-8
    # Content-Length: 35

    # User with this email already exists