POST http://localhost:8080/api/mobile/auth/login
Content-Type: application/json

{
    "email": "john_doe@example.com",
    "password": "the-amazing-spider-password"
}

# HTTP/1.1 200 OK
# Content-Type: application/json
# Content-Length: 313
# {
#   "acessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NDY2MzAwNjIsImlhdCI6MTc0NjYyNjQ2MiwidXNlcklkIjoiN2ZhMmE5ZGQtMWEyZi00ZGM2LTg3MzItOTkwM2Y2ZDE3MDEwIn0.9TFUwmWTAmOtyRdDNihcqhINI9_xbGR6esE_YP-mQvM",
#   "refreshToken": "fqU3PHa4OSBihQwfpHYq4NBFUlwy1kZryMhkwgGsrrJyHqW9KkOzjgeKozh-HRYZG1Yp_UKcOrA-7JTqHCmIfw"
# }

# Response 2:
    # HTTP/1.1 400 Bad Request
    # Content-Type: text/plain; charset=UTF-8
    # Content-Length: 19

    # Password is invalid
